// ChatStyle.js
import { Platform, StatusBar, StyleSheet } from "react-native";
import CommonStyles from "./CommonStyles";
import LayoutStyle from "./LayoutStyle";
import Colors from "./Colors";
import FontFamily from "../assets/fonts/FontFamily";
import { deviceHeight, deviceWidth } from "../utils/DeviceInfo";

const ChatStyle = StyleSheet.create({
	mainContainer: {
		...CommonStyles.mainContainer,
	},
	backgroundWhite: {
		...CommonStyles.backgroundWhite,
	},
	backgroundLightGray: {
		backgroundColor: Colors.lightGrayBG,
	},
	fullHeaderContainer: {
		...LayoutStyle.paddingBottom30,
		borderBottomEndRadius: 30,
		borderBottomStartRadius: 30,
	},
	headerContainer: {
		...CommonStyles.directionRowSB,
		...CommonStyles.mainPaddingH,
		...LayoutStyle.paddingBottom20,
		paddingTop: Platform.OS === "ios" ? 0 : "5%",
		marginTop: Platform.OS === "ios" ? -30 : 0,
	},
	headerText: {
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize18,
	},
	backArrow: {
		...LayoutStyle.paddingVertical10,
		...LayoutStyle.paddingRight20,
	},
	container: {
		...CommonStyles.mainPaddingH,
	},
	addPinContainer: {
		flexDirection: "row",
		...LayoutStyle.marginTop10,
	},
	pinDisplay: {
		alignContent: "center",
		alignSelf: "center",
	},
	pinImgContainer: {
		alignItems: "center",
	},
	pinContactImg: {
		height: 45,
		width: 45,
		borderRadius: 30,
	},
	retyrnPin: {
		height: 29,
		width: 29,
	},
	retyrnPinContainer: {
		backgroundColor: Colors.primary,
		// ...LayoutStyle.padding10,
		height: 46,
		width: 46,
		borderRadius: 23,
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.marginHorizontal10,
	},
	retyrnPinTex: {
		fontFamily: FontFamily.PoppinsMedium,
		color: Colors.labelBlack,
		textAlign: "center",
		...LayoutStyle.marginLeft10,
		...LayoutStyle.fontSize6,
		...LayoutStyle.marginTop10,
	},
	pinContactName: {
		fontFamily: FontFamily.PoppinsMedium,
		textAlign: "center",
		flexWrap: "wrap",
		width: 60,
		color: Colors.labelBlack,
		...LayoutStyle.fontSize6,
		...LayoutStyle.marginTop10,
	},
	listContainer: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingHorizontal20,
	},
	contactImg: {
		height: 40,
		width: 40,
		borderRadius: 20,
	},
	profileImg: {
		height: 40,
		width: 40,
		borderRadius: 20,
		justifyContent: "center",
		backgroundColor: Colors.primary,
	},
	textColor: {
		alignSelf: "center",
		fontFamily: FontFamily.PoppinsMedium,
		color: Colors.labelWhite,
		...LayoutStyle.fontSize18,
	},
	svgTextContain: { ...CommonStyles.directionRowCenter },
	addPinText: {
		...LayoutStyle.fontSize6,
		fontFamily: FontFamily.PoppinsMedium,
		textAlign: "center",
		color: Colors.secondary,
		...LayoutStyle.marginTop10,
	},
	contactName: {
		fontFamily: FontFamily.PoppinsSemiBold,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
		lineHeight: 20,
	},
	contactContainer: {
		...LayoutStyle.marginLeft20,
	},
	msg: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize8,
		color: Colors.labelDarkGray,
		lineHeight: 12,
	},
	msgDate: {
		fontFamily: FontFamily.PoppinsRegular,
		color: Colors.labelDarkGray,
		lineHeight: 12,
		fontSize: 8,
	},
	borderBottomGray: {
		borderBottomColor: Colors.cardBorder,
		borderBottomWidth: 1,
		...LayoutStyle.marginTop10,
	},
	// Message screen design start
	megHeader: {
		backgroundColor: Colors.white,
	},
	megHeaderContainer: {
		...CommonStyles.mainPaddingH,
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginTop20,
	},
	msgProfileHeader: {
		...CommonStyles.directionRowCenter,
	},
	megStatusBar: {
		...LayoutStyle.paddingBottom20,
		paddingTop: Platform.OS === "ios" ? 0 : "5%",
		marginTop: Platform.OS === "ios" ? -30 : 0,
	},
	nameHeader: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize18,
		color: Colors.labelBlack,
		lineHeight: 24,
	},
	dateHeader: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize8,
		color: Colors.labelDarkGray,
		lineHeight: 14,
	},
	borderBottomBlack: {
		borderBottomColor: Colors.darkBorder,
		borderBottomWidth: 1,
		marginTop: 14,
		...LayoutStyle.marginHorizontal20,
	},
	nameDate: {
		...LayoutStyle.marginLeft10,
		// height: 22,
	},
	profileDetailsLabel: {
		fontFamily: FontFamily.PoppinsSemiBold,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
	},
	profileDetailsValue: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize14,
		color: Colors.labelBlack,
	},
	detailsContainer: {
		...CommonStyles.directionRowSB,
		paddingVertical: Platform.OS === "ios" ? "4%" : "3.5%",
		paddingBottom: 0,
	},
	profileBG: {
		backgroundColor: Colors.primaryBG20,
		...LayoutStyle.paddingHorizontal20,
		...LayoutStyle.paddingVertical10,
		...LayoutStyle.marginTop10,
	},
	messagesContainer: {
		flexGrow: 1,
		justifyContent: "flex-end",
		paddingHorizontal: 12,
		paddingVertical: 16,
	},
	mainImgInputContainer: {
		flexDirection: "row",
		...LayoutStyle.marginBottom20,
		alignItems: "center",
	},
	messageContainer: {
		flexDirection: "row",
		...LayoutStyle.marginBottom10,
		...LayoutStyle.paddingHorizontal10,
	},
	senderMessageContainer: {
		justifyContent: "flex-end",
	},
	receiverMessageContainer: {
		justifyContent: "flex-start",
	},
	messageBox: {
		maxWidth: "65%",
		...LayoutStyle.marginBottom10,
	},
	messageBubble: {
		flex: 1,
		borderRadius: 7,
		paddingVertical: 6,
		paddingHorizontal: 10,
	},
	msgImgBubble: {
		width: deviceWidth / 1.7,
		borderRadius: 8,
		alignItems: "center",
		backgroundColor: Colors.lightGrayBG,
	},
	senderMessageBubble: {
		backgroundColor: Colors.primary,
		alignSelf: "flex-end",
	},
	receiverMessageBubble: {
		backgroundColor: Colors.lightGrayBG,
	},
	senderMsgImgBubble: {
		width: deviceWidth / 1.7,
		backgroundColor: Colors.primary,
		borderTopStartRadius: 8,
		borderTopEndRadius: 8,
		...LayoutStyle.paddingHorizontal10,
		...LayoutStyle.paddingTop10,
		paddingBottom: 5,
	},
	receiverMsgImgBubble: {
		width: deviceWidth / 1.8,
		backgroundColor: Colors.lightGrayBG,
		borderTopStartRadius: 8,
		borderTopEndRadius: 8,
		borderBottomWidth: 1,
		borderBottomColor: Colors.darkBorder,
		...LayoutStyle.paddingHorizontal10,
		...LayoutStyle.paddingTop10,
		paddingBottom: 5,
	},
	messageText: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize12,
	},
	messageImg: {
		// Single image UI
		width: deviceWidth / 1.7,
		height: deviceHeight / 6,
		alignSelf: "center",
		borderBottomRightRadius: 8,
		borderBottomLeftRadius: 8,
	},
	multipleImgs: {
		height: deviceHeight / 9.5,
		width: deviceWidth / 4,
		borderRadius: 8,
		alignItems: "center",
	},
	multipleImgsContainer: {
		// ...LayoutStyle.padding10,
		borderColor: Colors.darkBorder,
		borderRadius: 8,
	},
	attachButton: {
		...LayoutStyle.paddingHorizontal10,
	},
	sendButton: {
		...LayoutStyle.paddingRight10,
		paddingLeft: 12,
	},
	imgWithMesg: {
		backgroundColor: Colors.lightGrayBG,
		width: deviceWidth / 1.3,
		justifyContent: "center",
		alignSelf: "center",
		borderRadius: 30,
		paddingTop: 14,
	},
	inputIMG: {
		minHeight: 40,
		maxHeight: 120,
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsMedium,
		backgroundColor: Colors.lightGrayBG,
		width: deviceWidth / 1.4,
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "center",
		borderWidth: 0, // Remove border
		...LayoutStyle.fontSize12,
		borderRadius: 30,
	},
	input: {
		minHeight: 40,
		maxHeight: 120,
		lineHeight: 24,
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsMedium,
		backgroundColor: Colors.lightGrayBG,
		width: deviceWidth / 1.3,
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "center",
		borderWidth: 0, // Remove border
		...LayoutStyle.fontSize12,
		borderRadius: 30,
		...LayoutStyle.paddingHorizontal20,
	},
	inputImgBorder: {
		borderTopWidth: 1,
		marginTop: 16,
		borderColor: Colors.userBorder,
	},
	messageTime: {
		alignSelf: "flex-end",
		marginTop: 4,
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize8,
		color: Colors.labelBlack,
		...LayoutStyle.marginLeft10,
	},
	profileIcon: {
		width: 15,
		height: 15,
		borderRadius: 15,
		...LayoutStyle.marginRight10,
	},
	senderProfileBox: {
		width: 15,
		height: 15,
		borderRadius: 15,
		...LayoutStyle.marginRight10,
		backgroundColor: Colors.primary,
		justifyContent: "center",
		alignItems: "center",
	},
	senderProfile: {
		height: "100%",
		width: "100%",
		borderRadius: 12,
	},
	shareIconOption: {
		...LayoutStyle.padding20,
		...LayoutStyle.marginTop10,
		backgroundColor: Colors.lightBlue,
	},
	shareIconContainer: {
		...CommonStyles.directionRowSB,
	},
	iconWidth: {
		width: "20%",
		alignItems: "center",
	},
	iconShare: {
		...LayoutStyle.padding10,
		borderWidth: 1,
		borderRadius: 50,
	},
	shareIconText: {
		...LayoutStyle.fontSize6,
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.marginTop10,
		color: Colors.labelBlack,
	},
	optionImgContainer: {
		...LayoutStyle.padding20,
	},
	optionImg: {
		...CommonStyles.directionRowCenter,
	},
	optionIconContainer: {
		width: "18%",
		alignItems: "center",
		paddingVertical: 12,
		paddingHorizontal: 6,
		borderRadius: 4,
		backgroundColor: Colors.primary,
	},
	inputBoxselectImgs: {
		width: 60,
		height: 40,
		borderRadius: 4,
		...LayoutStyle.marginTop10,
	},
	selectImgs: {
		width: 60,
		height: 40,
		borderRadius: 4,
	},
	overlayDetele: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: Colors.secondary60,
		borderRadius: 4,
		width: 60,
		height: 40,
	},
	setDeleteIcon: {
		marginTop: -30,
		zIndex: 999999,
		alignItems: "center",
		alignSelf: "center",
	},
	fileMainContainer: {
		borderWidth: 1,
		padding: 2,
		borderRadius: 3,
		borderColor: Colors.secondary,
	},
	fileNameText: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize4,
		width: 40,
		paddingLeft: 2,
		color: Colors.secondary,
	},
	fileContainer: {
		justifyContent: "space-between",
		flexDirection: "row",
		width: 60,
	},
	iconPDF: { paddingVertical: 2, paddingLeft: 2 },
	// List of pass screen with selected check box
	passContainer: {
		flex: 1,
		...CommonStyles.directionRowSB,
		...CommonStyles.mainPaddingH,
	},
	cardContainer: {
		width: "100%",
		justifyContent: "center",
		borderWidth: 1,
		elevation: 5,
	},
	cardTitle: {
		fontFamily: FontFamily.PoppinsSemiBold,
		color: Colors.labelWhite,
		...LayoutStyle.fontSize16,
		...LayoutStyle.marginLeft20,
		width: "60%",
		flexWrap: "wrap",
	},
	cardType: {
		fontFamily: FontFamily.PoppinsMedium,
		color: Colors.inputLabel,
		...LayoutStyle.fontSize6,
		...LayoutStyle.marginRight20,
	},
	passMainContainer: {
		borderRadius: 3,
	},
	selectPassContainer: {
		width: 50,
		height: 50,
		alignItems: "flex-end",
		alignSelf: "flex-end",
	},
	passImgBG: {
		width: 50,
		height: 50,
	},
	passChatImg: {
		width: deviceHeight / 6,
		height: deviceWidth / 3.5,
		borderRadius: 8,
	},
	passChatContainer: {
		width: deviceHeight / 5.2,
		borderWidth: 1,
		alignItems: "center",
		borderColor: Colors.primary,
		...LayoutStyle.paddingTop10,
		borderRadius: 8,
		borderColor: Colors.darkBorder,
	},
	passChatName: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize8,
		color: Colors.labelBlack,
		...LayoutStyle.marginVertical10,
	},
	// Location Map modal
	actionModal: {
		...LayoutStyle.padding20,
		backgroundColor: Colors.white,
		borderRadius: 12,
	},
	centerModal: {
		...CommonStyles.directionRowSB,
	},
	modalHeader: {
		fontFamily: FontFamily.PoppinsSemiBold,
		...LayoutStyle.fontSize16,
		color: Colors.labelBlack,
	},
	mapContainer: {
		...LayoutStyle.marginTop10,
		borderRadius: 10,
		overflow: "hidden",
	},
	mapModal: {
		width: "100%",
		height: 300,
	},
	loaderHeight: {
		width: "100%",
		height: 300,
		alignItems: "center",
		justifyContent: "center",
	},
	mapSetBtn: {
		...LayoutStyle.padding10,
		...LayoutStyle.marginVertical20,
		alignItems: "center",
		borderRadius: 10,
	},
	mapTextBtn: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize12,
		color: Colors.labelWhite,
	},
	locationContainer: {
		height: 150,
		width: deviceWidth / 2,
		borderRadius: 8,
		overflow: "hidden",
	},
	smallLocationContainer: {
		borderRadius: 7,
		overflow: "hidden",
		...LayoutStyle.marginHorizontal20,
		width: 80,
		elevation: 5,
	},
	smallChatMap: {
		height: 70,
		width: 80,
		borderRadius: 10,
		overflow: "hidden",
	},
	chatMap: {
		...StyleSheet.absoluteFillObject,
	},
	notFountText: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
		textAlign: "center",
	},
	selectedPin: {
		height: 20,
		width: 20,
		borderRadius: 10,
		borderWidth: 4.5,
		borderColor: "#4CA7DA",
		backgroundColor: "#FFF",
	},
	selectPin: {
		height: 20,
		width: 20,
		borderRadius: 10,
		borderWidth: 1.5,
		borderColor: "#4CA7DA",
	},
	countContainer: {
		justifyContent: "center",
		alignItems: "center",
		width: "100%",

		paddingHorizontal: 20,
		paddingVertical: 15,
		backgroundColor: "#fff",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 5,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
	},
	pinCountTxt: {
		color: "#252525",
		fontSize: 14,
		fontWeight: "600",
		marginTop: 10,
	},
	addBtn: {
		backgroundColor: "#4CA7DA",
		paddingVertical: 12,
		width: "80%",
		borderRadius: 20,
		paddingHorizontal: "10",
		justifyContent: "center",
		alignItems: "center",
		marginTop: 18,
	},
	chatBox: {
		paddingVertical: 10,
		borderBottomWidth: 0.5,
		borderBottomColor: "rgba(13,34,61,0.4)",
	},
	badgeCount: {
		backgroundColor: "#4CA7DA",
		height: 13,
		width: 13,
		borderRadius: 6.5,
		position: "absolute",
		top: 3,
		right: -5,
		justifyContent: "center",
		alignItems: "center",
		zIndex: 999,
	},
	statusCircle: {
		backgroundColor: "#31ce36",
		height: 10,
		width: 10,
		borderRadius: 5,
		position: "absolute",
		bottom: 2,
		right: 0,
		justifyContent: "center",
		alignItems: "center",
		zIndex: 999,
	},
	countText: {
		color: Colors.white,
		fontSize: 7,
		fontWeight: "700",
	},
	flexCenter: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	emptyText: {
		textAlign: "center",
		fontSize: 12.5,
	},
	emptyTextBold: {
		marginTop: 20,
		fontSize: 16,
		fontWeight: "700",
		color: Colors.black,
	},
	scene: {
		flex: 1,
	},
	tabBar: {
		backgroundColor: "transparent",
		elevation: 0,
		marginHorizontal: 10,
	},
	inviteBtn: {
		paddingVertical: 5,
		width: 60,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: Colors.primary,
	},
	emergencyBtn: {
		paddingVertical: 5,
		paddingHorizontal: 7,
		borderRadius: 15,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: Colors.lightGrayBG,
		marginLeft: 5,
	},
	addrContainer: {
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.marginVertical20,
	},
	addressDisplay: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
	},
	actionIconContainer: {
		...CommonStyles.directionRowSB,
	},
	actionIconsView: {
		alignItems: "center",
		borderRadius: 6,
		width: "31.5%",
		...LayoutStyle.paddingVertical20,
	},
	iconText: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize8,
		marginTop: "8%",
		color: Colors.labelBlack,
	},
	fileMsg: {
		padding: 7,
		borderRadius: 8,
		width: "100%",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	rowSaperator: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
	},
	saperatorContainer: {
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: Colors.primary,
		padding: 10,
		borderRadius: 20,
		marginHorizontal: 7,
	},
	dateSeparatorText: {
		color: Colors.labelWhite,
		fontSize: 11,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	recenterButton: {
		position: "absolute",
		bottom: 5,
		left: 5,
		backgroundColor: Colors.white,
		padding: 5,
		borderRadius: 30,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		elevation: 5,
	},
	recenterTxt: {
		color: Colors.cardBlue,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	downArrowBtn: {
		position: "absolute",
		bottom: 70,
		right: 20,
	},
	downArrow: {
		backgroundColor: Colors.lightGrayBG,
		borderRadius: 20,
		padding: 3,
	},
	actionIcon: {
		...LayoutStyle.paddingRight20,
	},
	chatPassImgBackground: {
		width: deviceHeight / 4.3,
		height: deviceWidth / 3,
		borderRadius: 8,
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
	},
	chatPassFill: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0, 0, 0, 0.55)",
		borderRadius: 8,
	},
	chatPassImgBox: {
		width: "90%",
		height: "90%",
		justifyContent: "center",
		alignItems: "center",
	},
	chatPassImg: {
		width: "100%",
		height: "100%",
		borderRadius: 8,
		// backgroundColor: "rgba(0,0,0,0.6)",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 5,
	},
	dropArrowCount: {
		position: "absolute",
		top: -5,
		right: -10,
		backgroundColor: Colors.primary,
		borderRadius: 20,
		paddingHorizontal: 6,
		paddingVertical: 2,
		zIndex: 999,
	},
	dropArrowTxt: {
		color: Colors.white,
		fontSize: 10,
		fontWeight: FontFamily.PoppinsSemiBold,
	},
	actionMoreBtn: {
		position: "absolute",
		zIndex: 999,
		right: 20,
	},
	actionMoreTxt: {
		color: Colors.linkBtn,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginLeft: 1,
		textAlignVertical: "center",
	},
	readMoreBtn: {
		justifyContent: "center",
		marginTop: 5,
	},
	readMoreTxt: {
		color: Colors.linkBtn,
		textAlign: "right",
	},
	msgTime: {
		alignSelf: "flex-end",
		fontFamily: FontFamily.PoppinsRegular,
		color: Colors.labelDarkGray,
		...LayoutStyle.fontSize8,
		marginRight: 5,
		top: 1,
	},
	timeMsgRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-end",
		marginTop: 3,
	},
	keyboardAnimatedView: {
		paddingHorizontal: 10,
		paddingTop: 10,
		backgroundColor: Colors.white,
	},
	removePinnedPosition: {
		position: "absolute",
		zIndex: 9999,
		right: 5,
		top: 0,
	},
	pinnedBadgeCount: {
		backgroundColor: "#4CA7DA",
		height: 13,
		width: 13,
		borderRadius: 6.5,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		zIndex: 999,
		right: 5,
		top: 0,
	},
	adminBadgeCount: {
		backgroundColor: "#4CA7DA",
		height: 12,
		width: 12,
		borderRadius: 6,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		zIndex: 999,
		right: 2,
		top: 0,
	},
	statusText: {
		color: Colors.labelDarkGray,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
	},
	trustedContainer: {
		paddingVertical: 10,
		borderBottomWidth: 0.5,
		borderBottomColor: "rgba(13,34,61,0.4)",
	},
	trunculateTxt: {
		fontFamily: FontFamily.PoppinsRegular,
	},
	youTxt: {
		...LayoutStyle.fontSize8,
		color: Colors.labelDarkGray,
		fontFamily: FontFamily.PoppinsRegular,
		lineHeight: 16,
		marginLeft: 3,
	},
	lastMsgCreated: {
		textAlign: "right",
		top: 5,
	},
	youCompanyTxt: {
		...LayoutStyle.fontSize8,
		color: Colors.labelDarkGray,
		width: 160,
		fontFamily: FontFamily.PoppinsRegular,
		lineHeight: 16,
		marginLeft: 3,
	},
	messageList: {
		flexGrow: 1,
		paddingTop: 10,
	},
	screenHeader: {
		paddingTop: Platform.OS === "ios" ? 30 : 20,
	},
	headerProfileImg: {
		height: "100%",
		width: "100%",
		borderRadius: 20,
	},
	offlineBtn: {
		paddingVertical: 7,
		paddingHorizontal: 16,
		backgroundColor: Colors.secondary,
		borderRadius: 20,
	},
	offlineTxt: {
		color: Colors.white,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	emptyMsgList: {
		flex: 1,
		height: deviceHeight / 1.3,
	},
	attachmentList: {
		flexGrow: 1,
		justifyContent: "flex-start",
	},
	locationPopup: {
		height: deviceHeight / 3,
		justifyContent: "center",
	},
	fileDownloadTxt: {
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
		color: Colors.labelBlack,
	},
	valueSuffix: {
		left: Platform.OS !== "ios" ? -6 : 0,
	},
	scrollKeyValue: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		borderBottomWidth: 1,
		borderBottomColor: Colors.lightBlueBorder,
		...LayoutStyle.paddingVertical10,
	},
	scrollKeyTxt: {
		width: "40%",
		fontFamily: FontFamily.PoppinsSemiBold,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
	},
	scrollValueTxt: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize14,
		color: Colors.labelBlack,
	},
});

export default ChatStyle;
