import React from "react";
import { Platform, StyleSheet, Dimensions } from "react-native";
import Colors from "./Colors";
import FontFamily from "../assets/fonts/FontFamily";
import CommonStyles from "./CommonStyles";
import LayoutStyle from "./LayoutStyle";

const { width: screenWidth, height: deviceHeight } = Dimensions.get("window");

export const styles = StyleSheet.create({
	container: {
		...StyleSheet.absoluteFillObject,
		justifyContent: "flex-end",
		alignItems: "center",
	},
	map: {
		...StyleSheet.absoluteFillObject,
		//top: 50,
	},
	modal: {
		justifyContent: "flex-end",
		margin: 0,
	},
	modalWrapper: {
		width: screenWidth,
		alignItems: "center",
		maxHeight: "25%",
	},
	bordertop: {
		width: "100%",
		height: 20,
		backgroundColor: "#4CA7DA",
		borderTopRightRadius: 20,
		borderTopLeftRadius: 20,
	},
	modalContent: {
		width: "100%",
		backgroundColor: "#fff",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		padding: 20,
		alignItems: "center",
		marginTop: -18,
	},
	text: {
		fontSize: 14,
		color: "#252525",
		fontWeight: "700",
	},
	row: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
	},
	rowBetween: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	closeButton: {
		backgroundColor: "#f9f9f9",
		padding: 3,
		borderRadius: 5,
	},
	div: {
		height: 2,
		borderColor: "#EFEFEF",
		borderWidth: 1,
		borderRadius: 5,
		marginVertical: 15,
	},
	timeTxt: {
		fontSize: 10,
		color: "#252525",
		fontWeight: "700",
	},
	addressTxt: {
		fontSize: 12,
	},
	startBtn: {
		borderWidth: 1,
		borderColor: Colors.secondary,
		borderRadius: 30,
		paddingVertical: 3,
		paddingHorizontal: 15,
	},
	startTxt: {
		fontSize: 12,
		color: Colors.secondary,
		fontWeight: "500",
	},
	navigationBar: {
		position: "absolute",
		top: Platform.OS === "ios" ? 55 : 45,
		width: "95%",
	},
	directionContainer: {
		paddingHorizontal: 20,
		paddingVertical: 10,
		backgroundColor: "rgba(13, 34, 61, 0.89)",
		justifyContent: "center",
		borderTopLeftRadius: 10,
		borderTopRightRadius: 10,
		borderBottomRightRadius: 10,
	},
	thenContainer: {
		backgroundColor: "#0D223D",
		paddingHorizontal: 20,
		paddingVertical: 5,
		marginTop: 10,
		borderTopRightRadius: 7,
		borderBottomLeftRadius: 5,
		borderBottomRightRadius: 5,
		width: "22%",
		height: 35,
	},
	rowOnly: {
		flexDirection: "row",
		alignItems: "center",
	},
	wayLocation: {
		fontSize: 20,
		color: Colors.white,
		fontWeight: "400",
	},
	wayTxt: {
		fontSize: 12,
		color: Colors.white,
		fontWeight: "300",
	},
	towardLocation: {
		fontSize: 16,
		color: Colors.white,
		fontWeight: "400",
	},
	columnCenter: {
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
	},
	thenTxt: {
		color: Colors.white,
		fontSize: 12,
		marginRight: 3,
	},
	optionsContainer: {
		marginTop: 10,
		// paddingHorizontal: 20,
	},
	optionBtn: {
		backgroundColor: "#0D223D",
		height: 40,
		width: 40,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	directionDurationTxt: {
		color: Colors.black,
		fontSize: 12,
		fontWeight: "600",
	},
	closePanelBtn: {
		backgroundColor: "#F5F5F5",
		height: 40,
		width: 40,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	recenterButton: {
		position: "absolute",
		bottom: 30,
		left: 10,
		backgroundColor: Colors.white,
		padding: 12,
		borderRadius: 30,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		elevation: 5,
	},
	recenterTxt: {
		color: Colors.cardBlue,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	pinWhiteContainer: {
		padding: 3,
		borderRadius: 999,
		backgroundColor: Colors.white,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 0.2,
		borderColor: Colors.labelDarkGray,

		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.2,
		shadowRadius: Platform.OS === "android" ? 10 : 35,
		elevation: 8,
	},
	pinIconContainer: {
		padding: 3,
		borderRadius: 999,
		backgroundColor: "#f50150",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 4,
	},
	MapLocationIconContainer: {
		height: 24,
		width: 24,
		borderRadius: Platform.OS === "android" ? 12 : 26,
		backgroundColor: Colors.white,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 0.2,
		borderColor: Colors.labelDarkGray,

		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.5,
		shadowRadius: Platform.OS === "android" ? 10 : 35,
		elevation: 8,
	},
	parkingIconContainer: {
		height: 18,
		width: 18,
		borderRadius: 9,
		backgroundColor: Colors.red,
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 4,
	},
	parkingIconTxt: {
		color: Colors.white,
		fontSize: 10,
		fontFamily: FontFamily.PoppinsMedium,
	},
	closeBtn: {
		position: "absolute",
		top: 40,
		right: 10,
		backgroundColor: "#F5F5F5",
		padding: 12,
		borderRadius: 5,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.5,
		shadowRadius: Platform.OS === "android" ? 10 : 35,
		elevation: 8,
	},
	closeBtnIOS: {
		position: "absolute",
		top: 65,
		left: 10,
		backgroundColor: "#F5F5F5",
		padding: 12,
		borderRadius: 5,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.5,
		shadowRadius: Platform.OS === "android" ? 10 : 35,
		elevation: 8,
	},
	mapOptionRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginVertical10,
	},
	mapOptionBtn: {
		backgroundColor: Colors.red,
		...LayoutStyle.padding10,
		width: "30%",
		borderRadius: 4,
		alignItems: "center",
		justifyContent: "center",
	},
	destiIndexContainer: {
		flex: 1,
		paddingHorizontal: 6,
	},
	positionReletiveCenter: {
		position: "relative",
		alignItems: "center",
		justifyContent: "center",
	},
	indexContainer: {
		height: 12,
		width: 12,
		borderRadius: 6,
		backgroundColor: Colors.white,
		borderWidth: 0.5,
		borderColor: "#E5E5E5",
		position: "absolute",
		bottom: 0,
		right: -5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 8,
	},
	indexTxt: {
		fontSize: 10,
		fontFamily: FontFamily.PoppinsBold,
		color: Colors.labelBlack,
		textAlign: "center",
		textAlignVertical: "center",
		top: -1,
	},
});
