import { Platform, StatusBar, StyleSheet } from "react-native";
import CommonStyles from "./CommonStyles";
import LayoutStyle from "./LayoutStyle";
import Colors from "./Colors";
import FontFamily from "../assets/fonts/FontFamily";
import { deviceHeight, deviceWidth } from "../utils/DeviceInfo";
import { blue } from "react-native-reanimated/lib/typescript/Colors";
import ComponentStyles from "./ComponentStyles";

const MapStyle = StyleSheet.create({
	mainContainer: {
		...CommonStyles.mainContainer,
	},
	backgroundWhite: {
		...CommonStyles.backgroundWhite,
	},
	// Tab navigation style
	tabLabelStyle: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize10,
		textTransform: "none",
	},
	mapInputContainer: {
		...CommonStyles.mainPadding,
		backgroundColor: Colors.white,
		borderBottomLeftRadius: 30,
		borderBottomRightRadius: 30,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,

		elevation: 2,
	},
	headerText: {
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize14,
	},
	mapInputStyle: {
		height: 50,
		width: "90%",
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize14,
		...LayoutStyle.marginLeft10,
		marginTop: Platform.OS === "android" ? 2 : 0,
	},
	navigationIcon: {
		...LayoutStyle.padding10,
		borderRadius: 50,
	},
	naviIconContainer: {
		backgroundColor: Colors.navigationIcon,
		borderRadius: 50,
		marginBottom: "30%",
	},
	goText: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize20,
		color: Colors.labelWhite,
		paddingHorizontal: 2,
		paddingTop: 3,
	},
	// List of again destination
	headerTextPadding: {
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize14,
		...LayoutStyle.paddingBottom10,
	},
	listContainer: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginTop10,
	},
	svgTextContain: {
		...CommonStyles.directionRowCenter,
	},
	destinationLabel: {
		fontFamily: FontFamily.PoppinsSemiBold,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
		// lineHeight: 18,
	},
	destinationValue: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize8,
		color: Colors.labelDarkGray,
		// lineHeight: 16,
	},
	actionIcon: {
		...LayoutStyle.paddingVertical10,
		...LayoutStyle.paddingLeft20,
	},
	cityBG: {
		borderRadius: 5,
		...LayoutStyle.marginRight10,
		padding: "4%",
		width: 64,
		justifyContent: "center",
		alignItems: "center",
	},
	borderBottomGray: {
		borderBottomColor: Colors.cardBorder,
		borderBottomWidth: 1,
		...LayoutStyle.marginTop10,
	},
	// List style completed
	// Open modal
	actionModal: {
		...LayoutStyle.padding20,
		backgroundColor: Colors.white,
		borderRadius: 12,
	},
	modalHeader: {
		fontFamily: FontFamily.PoppinsSemiBold,
		...LayoutStyle.fontSize16,
		color: Colors.labelBlack,
	},
	shareModalCenter: {
		flexGrow: 1,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: Colors.blackTransparent,
		...LayoutStyle.padding15,
		marginTop: "20%",
	},
	centerModal: {
		...CommonStyles.directionRowSB,
	},
	addrContainer: {
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.marginVertical20,
	},
	addressDisplay: {
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
	},
	actionIconContainer: {
		...CommonStyles.directionRowSB,
	},
	actionIconsView: {
		alignItems: "center",
		borderRadius: 6,
		width: "31.5%",
		...LayoutStyle.paddingVertical20,
	},
	iconText: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize8,
		marginTop: "8%",
		color: Colors.labelBlack,
	},
	// Trip design start
	mapCardContainer: {
		backgroundColor: Colors.primary,
		...LayoutStyle.paddingHorizontal20,
		...LayoutStyle.paddingBottom30,
		borderBottomLeftRadius: 20,
		borderBottomRightRadius: 20,
		overflow: "hidden",
	},
	mapImgContainer: {
		height: deviceHeight / 4.5,
	},
	tripDetailsText: {
		...LayoutStyle.fontSize16,
		color: Colors.white,
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.paddingBottom20,
	},
	tripDetailsDesti: {
		backgroundColor: Colors.lightGrayBG,
		...LayoutStyle.padding20,
	},
	originIcon: {
		padding: "1.7%",
		backgroundColor: Colors.primary,
		borderRadius: 10,
		marginLeft: "2.5%",
	},
	balckCircle: {
		backgroundColor: Colors.primary,
		height: 10,
		width: 10,
		borderRadius: 5,
		marginLeft: "2.5%",
	},
	destinationTitle: {
		...LayoutStyle.fontSize16,
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.marginBottom10,
	},
	originContainer: {
		...CommonStyles.directionRowCenter,
	},
	originAddrText: {
		...LayoutStyle.fontSize12,
		...LayoutStyle.paddingLeft10,
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsRegular,
	},
	destiContainer: {
		...CommonStyles.directionRowCenter,
	},
	destiAddrText: {
		...LayoutStyle.fontSize12,
		...LayoutStyle.paddingLeft10,
		color: Colors.labelBlue,
		fontFamily: FontFamily.PoppinsRegular,
	},
	destiIcon: {
		padding: "1.5%",
		backgroundColor: Colors.secondary,
		marginLeft: "2.5%",
	},
	blueBox: {
		backgroundColor: Colors.secondary,
		height: 10,
		width: 10,
		marginLeft: "2.5%",
	},
	destiButton: {
		...LayoutStyle.paddingBottom20,
	},
	scoreCard: {
		backgroundColor: Colors.white,
		...LayoutStyle.padding20,
	},
	startText: {
		...LayoutStyle.marginLeft10,
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.fontSize12,
		color: Colors.labelBlack,
	},
	startBtn: {
		borderWidth: 1,
		borderColor: Colors.secondary,
		borderRadius: 20,
		...LayoutStyle.paddingVertical10,
		paddingLeft: 12,
		paddingRight: 12,
	},
	historyContainer: {
		...LayoutStyle.marginVertical20,
	},
	loaclContainer: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginTop20,
		flex: 1,
	},
	loaclCard: {
		...LayoutStyle.paddingTop20,
		...LayoutStyle.paddingBottom20,
		borderRadius: 4,
		flex: 0.3,
	},
	directionLoaclCard: {
		...LayoutStyle.padding10,
		borderRadius: 4,
	},
	localText: {
		fontFamily: FontFamily.PoppinsMedium,
		color: Colors.white,
		...LayoutStyle.fontSize10,
		...LayoutStyle.marginTop10,
	},
	contactContainer: {
		...LayoutStyle.marginTop20,
		marginBottom: "10%",
	},
	borders: {
		borderBottomWidth: 1,
		borderBottomColor: Colors.userBorder,
	},
	profileImg: {
		height: 35,
		width: 35,
		borderRadius: 20,
	},
	textColor: {
		alignSelf: "center",
		textAlign: "center",
		fontFamily: FontFamily.PoppinsMedium,
		color: Colors.labelWhite,
		...LayoutStyle.fontSize18,
		marginTop: "15%",
	},
	darkName: {
		...LayoutStyle.fontSize12,
		fontFamily: FontFamily.PoppinsBold,
		color: Colors.labelBlack,
	},
	flexColumn: {
		flexDirection: "column",
		alignItems: "center",
	},
	originPrimaryCircle: {
		height: 10,
		width: 10,
		borderRadius: 5,
		backgroundColor: Colors.primary,
	},
	pathLine: {
		borderWidth: 0.7,
		borderColor: Colors.primary,
		height: 40,
		marginVertical: 2,
		backgroundColor: Colors.primary,
	},
	blueSquare: {
		height: 10,
		width: 10,
		borderRadius: 0,
		backgroundColor: "#4CA7DA",
	},
	scrollContainer: {
		maxHeight: 200, // Set the max height of the ScrollView
	},
	scrollContent: {
		// You can add padding or other content styling here if needed
	},
	deleteContainer: {
		paddingHorizontal: 20,
		paddingVertical: 15,
		backgroundColor: "#fff",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 5,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
	},
	rowBetween: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	originInputContainer: {
		...LayoutStyle.marginBottom10,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	originBox: {
		...CommonStyles.directionRowCenter,
		borderColor: Colors.secondary,
		borderWidth: 1,
		borderRadius: 25,
		alignItems: "flex-start",
		width: "95%",
	},
	originTextInput: {
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.fontSize12,
		...LayoutStyle.marginLeft10,
		height: 30,
		backgroundColor: "transparent",
		textAlign: "left",
		marginTop: Platform.OS === "android" ? 5 : 0,
	},
	originBtn: {
		backgroundColor: Colors.inputfillBG,
		height: 35,
		fontFamily: FontFamily.PoppinsRegular,
		...CommonStyles.directionRowCenter,
		...LayoutStyle.fontSize12,
		borderRadius: 25,
		...LayoutStyle.paddingHorizontal20,
	},
	row: {
		flexDirection: "row",
		alignItems: "center",
		width: "100%",
	},
	expandCollapseBtn: {
		position: "absolute",
		bottom: 5,
		right: 5,
	},
	emptyListContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		marginTop: "50%",
	},
	deleteIcon: {
		backgroundColor: Colors.iconGray,
		padding: 3,
		borderRadius: 5,
	},
	againTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 20,
	},
	emergencyDes: {
		textAlign: "center",
		fontSize: 10,
		fontFamily: FontFamily.PoppinsRegular,
		color: Colors.red,
	},
	emergencyTitleContainer: {
		width: "100%",
		marginTop: 5,
		padding: 5,
		backgroundColor: Colors.inputfillBG,
		borderRadius: 3,
	},
	emergencyTitle: {
		fontSize: 12,
		color: Colors.inputBlackText,
	},
	contactRow: {
		...CommonStyles.directionRowSB,
		width: "100%",
		padding: 5,
		borderBottomWidth: 0.5,
		borderBottomColor: "#ccc",
	},
	ContactName: {
		fontSize: 12,
		color: Colors.inputBlackText,
		width: "57%",
	},
	ContactNum: {
		fontSize: 12,
		color: Colors.labelBlue,
	},
	contactIndex: {
		fontSize: 12,
	},
	mapContainer: {
		flex: 1,
		justifyContent: "flex-end",
		alignItems: "center",
	},
	goText: {
		color: "#fff",
		fontSize: 16,
		fontWeight: "bold",
	},
	tripDetailBottomBox: {
		backgroundColor: Colors.lightGrayBG,
		padding: 20,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: -2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 3.84,
		elevation: 5,
	},
	reachedModal: {
		...LayoutStyle.padding20,
		backgroundColor: Colors.white,
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: -2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 3.84,
		elevation: 5,
	},
	reachedLocationIcon: {
		position: "absolute",
		right: "50%",
		top: -20,
		backgroundColor: Colors.red,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		height: 45,
		width: 45,
		borderRadius: 22.5,
	},
	reachedTxtContainer: {
		justifyContent: "center",
		alignItems: "center",
		marginTop: 12,
	},
	arrivingTxt: {
		color: Colors.inputBlackText,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	arrivingLocation: {
		textAlign: "center",
		fontSize: 16,
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsMedium,
	},
	doneButton: {
		marginTop: 12,
		width: "100%",
	},
	userLocationContainer: {
		height: 22,
		width: 22,
		borderRadius: 11,
		padding: 5,
		backgroundColor: Colors.primary,
	},
	userLocationImage: {
		height: "100%",
		width: "100%",
		resizeMode: "contain",
	},
	durationTimePanel: {
		backgroundColor: Colors.primary,
		height: 80,
		zIndex: 999,
		borderTopLeftRadius: 30,
		borderTopRightRadius: 30,
		padding: 20,
		justifyContent: "center",
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
	},
	alignCenter: {
		justifyContent: "center",
		alignItems: "center",
	},
	timeDurationTxt: {
		color: Colors.white,
		fontSize: 10,
	},
	timeDistanceTxt: {
		color: Colors.white,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsBold,
	},
	navigationButton: {
		position: "absolute",
		padding: "4%",
		backgroundColor: Colors.navigationIcon,
		borderRadius: 50,
		justifyContent: "center",
		alignItems: "center",
		bottom: 50,
	},
	activeGoBtn: {
		padding: 10,
		backgroundColor: Colors.secondary,
		borderRadius: 50,
		justifyContent: "center",
		alignItems: "center",
	},
	inactiveGoBtn: {
		borderRadius: 70,
		height: 35,
		width: 35,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: Colors.transparent,
	},
	navigationButtonIos: {
		position: "absolute",
		bottom: 50,
		justifyContent: "center",
		alignItems: "center",
		height: 70,
		width: 70,
		borderRadius: 35,
		backgroundColor: Colors.navigationIcon,
	},
	activeGoBtnIos: {
		height: 44,
		width: 44,
		borderRadius: 22,
		padding: 10,
		backgroundColor: Colors.secondary,
		justifyContent: "center",
		alignItems: "center",
	},
	againDestiBtnBox: {
		width: "100%",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 5,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
		padding: 14,
		justifyContent: "center",
		backgroundColor: Colors.lightGrayBG,
	},
	swipeBtn: {
		width: 100,
		backgroundColor: "#DA4C4C",
		justifyContent: "center",
		alignItems: "center",
		borderBottomColor: "#ccc",
		borderBottomWidth: 1,
	},
	swipeBtnTxt: {
		color: "#fff",
		fontWeight: "600",
	},
	backMapRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		...LayoutStyle.marginHorizontal20,
		marginTop: StatusBar.currentHeight + 14,
	},
	backDirectionIos: {
		backgroundColor: Colors.white,
		justifyContent: "center",
		alignItems: "center",
		height: 40,
		width: 40,
		padding: 5,
		borderRadius: 5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.15,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
	},
	mapLayoutOption: {
		backgroundColor: Colors.white,
		borderRadius: 5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.15,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
	},
	navOptions: {
		position: "absolute",
		marginTop: 250,
		right: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	navLayoutOption: {
		backgroundColor: Colors.white,
		height: 50,
		width: 50,
		borderRadius: 25,
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.15,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
	},
	soundOptions: {
		backgroundColor: Colors.white,
		borderRadius: 30,
		marginTop: 10,
		padding: 4,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.15,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
	},
	soundOptionActive: {
		padding: 5,
		borderRadius: 25,
	},
	pipOptionActive: {
		borderRadius: 25,
		backgroundColor: "#F5F5F5",
		...LayoutStyle.marginTop10,
		...LayoutStyle.padding10,
	},
	searchRow: {
		...LayoutStyle.marginVertical20,
		...CommonStyles.directionRowSB,
	},
	searchContainer: {
		backgroundColor: Colors.transparent,
		...CommonStyles.directionRowCenter,
		flex: 1,
		borderWidth: 1,
		borderColor: Colors.secondary,
		borderRadius: 25,
		paddingHorizontal: 10,
		paddingVertical: Platform.OS === "ios" ? 10 : 0,
	},
	searchInput: {
		flex: 1,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	locationRow: {
		...LayoutStyle.paddingVertical10,
	},
	locationTxtBox: {
		flex: 1,
	},
	locationTxt: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	distanceTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	locationDesTxt: {
		flex: 1,
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	divDark: {
		backgroundColor: "#e5e5e5",
		height: 1,
	},
	suggestionContainer: {
		...LayoutStyle.paddingHorizontal10,
		...LayoutStyle.marginTop10,
		borderWidth: 1,
		borderColor: Colors.secondary,
		borderRadius: 10,
	},
	turnRow: {
		...CommonStyles.directionRowCenter,
		...LayoutStyle.paddingVertical10,
	},
	turnIcon: {
		justifyContent: "center",
		alignItems: "center",
		marginRight: 12,
	},
	turnDistacne: {
		fontSize: 16,
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsBold,
	},
	trunDesTxt: {
		color: Colors.labelDarkGray,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
	},
	div: {
		height: 1,
		backgroundColor: "#F5F5F5",
		marginVertical: 10,
	},
	pinIconContainer: {
		padding: 3,
		borderRadius: 999,
		backgroundColor: "#f50150",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 4,
	},
	markerWhiteBox: {
		backgroundColor: Colors.white,
		height: 50,
		width: 50,
		borderRadius: 25,
		padding: 4,
		justifyContent: "center",
		alignItems: "center",
	},
	markerBackground: {
		backgroundColor: "#ea3d6a",
		height: "100%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 25,
	},
	markerBottomPin: {
		position: "absolute",
		bottom: -11,
		justifyContent: "center",
		alignItems: "center",
	},
	pinkDot: {
		height: 5,
		width: 5,
		borderRadius: 2.5,
		backgroundColor: "#ea3d6a",
		top: 5,
	},
	locationInput: {
		...CommonStyles.directionRowSB,
		borderBottomWidth: 1,
		borderBottomColor: Colors.inputBorder,
	},
	filledLocationInput: {
		...CommonStyles.directionRowSB,
		paddingHorizontal: 20,
		paddingVertical: 2,
		borderRadius: 26,
		backgroundColor: Colors.primaryBG20,
	},
	rowFlex: {
		flex: 1,
		...CommonStyles.directionRowCenter,
	},
	adrsBlueTxt: {
		color: Colors.secondary,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	inputAddress: {
		flex: 1,
		...ComponentStyles.inputLabel,
		color: Colors.white,
		paddingVertical: 10,
	},
	mapLayoutImg: {
		height: 40,
		width: 30,
		resizeMode: "contain",
	},
	locStateCode: {
		color: Colors.labelDarkGray,
		fontSize: 22,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	noteContainer: {
		marginTop: 5,
		backgroundColor: Colors.white,
		padding: 10,
		borderRadius: 5,
	},
	addNoteTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	addNoteDesTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	noteInputContainer: {
		...LayoutStyle.marginTop10,
		...LayoutStyle.paddingHorizontal10,
		backgroundColor: Colors.white,
		borderTopLeftRadius: 7,
		borderTopRightRadius: 7,
	},
	noteInput: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
		textAlignVertical: "top",
		height: 120,
	},
	noteDiv: {
		height: 1,
		width: "100%",
		backgroundColor: "#F5F5F5",
	},
	noteLengthTxt: {
		color: Colors.labelDarkGray,
		fontSize: 11,
		fontFamily: FontFamily.PoppinsMedium,
		textAlign: "right",
		marginTop: 10,
	},
	noteBtnContainer: {
		...LayoutStyle.marginTop10,
		...LayoutStyle.padding10,
		backgroundColor: Colors.white,
		borderBottomLeftRadius: 7,
		borderBottomRightRadius: 7,
	},
	noteBtnRow: {
		...CommonStyles.directionRowCenter,
		justifyContent: "flex-end",
	},
	noteCancelBtn: {
		paddingVertical: 5,
		width: "30%",
		borderRadius: 5,
		backgroundColor: "#E5E5E5",
		justifyContent: "center",
		alignItems: "center",
		marginHorizontal: 5,
	},
	noteCancelBtnTxt: {
		color: Colors.labelDarkGray,
		fontSize: 13,
		fontFamily: FontFamily.PoppinsMedium,
	},
	noteSaveBtn: {
		paddingVertical: 5,
		width: "30%",
		borderRadius: 5,
		backgroundColor: Colors.secondary,
		justifyContent: "center",
		alignItems: "center",
		marginHorizontal: 5,
	},
	noteSaveTxt: {
		color: Colors.white,
		fontSize: 13,
		fontFamily: FontFamily.PoppinsMedium,
	},
	noteBox: {
		...LayoutStyle.paddingHorizontal20,
		...LayoutStyle.marginBottom20,
	},
	editNoteTxt: {
		color: Colors.secondary,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 3,
	},
	navigationIndicator: {
		backgroundColor: "rgba(255, 255, 255, 0.9)",
		height: 50,
		width: 50,
		borderRadius: 25,
		justifyContent: "center",
		alignItems: "center",
	},
	contactModal: {
		flex: 1,
		backgroundColor: Colors.white,
	},
	contactMContainer: {
		flex: 1,
	},
	contactMHeader: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingHorizontal20,
		...LayoutStyle.paddingVertical10,
	},
	originCircle: {
		width: 18,
		height: 18,
		borderRadius: 9,
		backgroundColor: "#dbdbdb",
		borderWidth: 3,
		borderColor: "#a3a3a3",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.2,
		shadowRadius: 1.41,
		elevation: 2,
	},
	pathBlueDot: {
		width: 8,
		height: 8,
		borderRadius: 8,
		backgroundColor: "#0f53fe",
		zIndex: -999,
	},
	pipDetailContainer: {
		// flex: 1,
		// flexDirection: "row",
		// alignItems: "center",
		// backgroundColor: "#313035",
		// paddingHorizontal: 8,
		// paddingVertical: 5,
		// position: "absolute",
		// bottom: 0,

		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 10,
		paddingVertical: 7,
		backgroundColor: "#313035",
	},
	pipTextCover: {
		flex: 1,
		marginLeft: 8,
		flexShrink: 1,
	},
	pipTurnPoint: {
		fontSize: 12,
		color: Colors.white,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	pipDistance: {
		fontSize: 11,
		color: Colors.white,
		fontFamily: FontFamily.PoppinsMedium,
	},
});

export default MapStyle;
