// create new pass
export const CREATE_PASS_REQUEST = "CREATE_PASS_REQUEST";
export const CREATE_PASS_SUCCESS = "CREATE_PASS_SUCCESS";
export const CREATE_PASS_FAIL = "CREATE_PASS_FAIL";

// Edit pass
export const EDIT_PASS_REQUEST = "EDIT_PASS_REQUEST";
export const EDIT_PASS_SUCCESS = "EDIT_PASS_SUCCESS";
export const EDIT_PASS_FAIL = "EDIT_PASS_FAIL";

// get all passes
export const PASSES_LIST_REQUEST = "PASSES_LIST_REQUEST";
export const PASSES_LIST_SUCCESS = "PASSES_LIST_SUCCESS";
export const PASSES_LIST_FAIL = "PASSES_LIST_FAIL";

// get archive passes
export const ARCHIVE_PASSSES_LIST_REQUEST = "ARCHIVE_PASSSES_LIST_REQUEST";
export const ARCHIVE_PASSES_LIST_SUCCESS = "ARCHIVE_PASSES_LIST_SUCCESS";
export const ARCHIVE_PASSES_LIST_FAIL = "ARCHIVE_PASSES_LIST_FAIL";

// Get pass deatils
export const PASS_DETAILS_REQUEST = "PASS_DETAILS_REQUEST";
export const PASS_DETAILS_SUCCESS = "PASS_DETAILS_SUCCESS";
export const PASS_DETAILS_FAIL = "PASS_DETAILS_FAIL";

export const STATE_LIST_REQUEST = "STATE_LIST_REQUEST";
export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_FAIL = "STATE_LIST_FAIL";
