import React from "react";
import { StyleSheet, Platform } from "react-native";
import Colors from "../../../../styles/Colors";
import FontFamily from "../../../../assets/fonts/FontFamily";
import LayoutStyle from "../../../../styles/LayoutStyle";
import CommonStyles from "../../../../styles/CommonStyles";
import { deviceHeight } from "../../../../utils/DeviceInfo";
import ComponentStyles from "../../../../styles/ComponentStyles";

export const styles = StyleSheet.create({
	flex: {
		flex: 1,
	},
	mainContainer: {
		flex: 1,
		paddingHorizontal: 20,
	},
	backgroundStyle: {
		flex: 1,
		backgroundColor: "#F6F6F6",
		...Platform.select({
			ios: {
				shadowColor: "#000",
				shadowOffset: { width: 0, height: -2 },
				shadowOpacity: 0.1,
				shadowRadius: 8,
			},
			android: {
				elevation: 10,
			},
		}),
	},
	header: {
		marginHorizontal: 20,
		paddingTop: Platform.OS === "ios" ? 10 : 0,
	},
	rowBetween: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	text: {
		fontSize: 14,
		color: "#252525",
		fontWeight: "700",
	},
	closePanelBtn: {
		backgroundColor: "#F5F5F5",
		height: 40,
		width: 40,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	div: {
		height: 2,
		borderColor: Colors.graySwipeBackground,
		borderWidth: 1,
		borderRadius: 5,
		marginVertical: 15,
	},
	searchRow: {
		...LayoutStyle.marginVertical20,
		...CommonStyles.directionRowSB,
	},
	searchContainer: {
		backgroundColor: "#e7e7e7",
		paddingHorizontal: 10,
		borderRadius: 5,
		...CommonStyles.directionRowCenter,
		paddingVertical: Platform.OS === "ios" ? 10 : 0,
		flex: 0.95,
	},
	searchInput: {
		flex: 1,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
		marginLeft: 5,
	},
	cancelSearchBtn: {
		paddingVertical: 10,
		alignItems: "center",
		justifyContent: "center",
	},
	cancelSearchTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		textAlignVertical: "center",
	},
	headerTxt: {
		color: Colors.labelDarkGray,
		fontSize: 15,
		fontFamily: FontFamily.PoppinsMedium,
	},
	library: {
		backgroundColor: Colors.white,
		padding: 10,
		borderRadius: 5,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: Platform.OS === "ios" ? 0 : -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 0,
		borderTopColor: "#ddd",
	},
	searchPlace: {
		backgroundColor: Colors.white,
		// padding: 10,
		borderRadius: 5,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 0,
		borderTopColor: "#ddd",
	},
	libraryBtn: {
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.marginRight20,
	},
	justifyCenter: {
		justifyContent: "center",
		alignItems: "center",
	},
	libraryIcon: {
		backgroundColor: Colors.graySwipeBackground,
		height: 54,
		width: 54,
		borderRadius: 28,
		justifyContent: "center",
		alignItems: "center",
	},
	libraryTag: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		lineHeight: 25,
	},
	libraryBlueTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 12,
	},
	div: {
		height: 1,
		backgroundColor: "#F5F5F5",
		marginVertical: 10,
	},
	topPanelDiv: {
		height: 0.3,
		backgroundColor: "#888",
	},
	divPopup: {
		height: 1,
		backgroundColor: "#E5E5E5",
	},
	libraryCountTxt: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	libraryCountTxtDot: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
		...LayoutStyle.marginHorizontal10,
	},
	titleHeaderRow: {
		...LayoutStyle.marginTop20,
		...LayoutStyle.marginBottom10,
		...CommonStyles.directionRowSB,
	},
	moreBtnTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 15,
	},
	directionCircle: {
		height: 30,
		width: 30,
		borderRadius: 15,
		backgroundColor: "#4d4d4d",
		justifyContent: "center",
		alignItems: "center",
		marginRight: 10,
	},
	recentDestination: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
		lineHeight: 25,
	},
	fromLocationTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	addPinTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	shareBtn: {
		backgroundColor: "#E8E8E8",
		justifyContent: "center",
		alignItems: "center",
		padding: 10,
		borderRadius: 5,
	},
	shareBtnTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	termsTxt: {
		color: Colors.labelDarkGray,
		fontSize: 11,
		bottom: 1,
	},

	recentTitle: {
		color: Colors.labelBlack,
		fontSize: 22,
		fontFamily: FontFamily.PoppinsBold,
	},
	headerSmallBtn: {
		backgroundColor: "#e5e7e4",
		padding: 7,
		borderRadius: 17,
		justifyContent: "center",
		alignItems: "center",
	},
	closeBtn: {
		backgroundColor: "#e5e7e4",
		height: 30,
		width: 30,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	divDark: {
		backgroundColor: "#e5e5e5",
		height: 1,
	},
	searchedRow: {
		...CommonStyles.directionRowCenter,
		...LayoutStyle.marginVertical10,
	},
	searchedIcon: {
		...LayoutStyle.marginRight10,
		bottom: 1,
	},
	nearByIcon: {
		...LayoutStyle.marginRight10,
		height: 36,
		width: 36,
		borderRadius: 18,
		backgroundColor: Colors.blueActiveBtn,
		justifyContent: "center",
		alignItems: "center",
		bottom: 0,
	},
	searchedDestination: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	middleDot: {
		color: Colors.labelDarkGray,
		fontSize: 16,
	},
	searchedDestiCity: {
		color: Colors.labelDarkGray,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	suggestionDesTxt: {
		color: Colors.labelDarkGray,
		fontFamily: FontFamily.PoppinsRegular,
		fontSize: 14,
		// lineHeight: 15,
	},
	suggestionRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginVertical10,
	},
	headerActionBtnTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	headerDetailTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	selectedLabel: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	selectedAddress: {
		color: Colors.labelDarkGray,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsRegular,
	},
	addPersonIcon: {
		backgroundColor: "#e5e5e5",
		height: 25,
		width: 25,
		borderRadius: 12.5,
		justifyContent: "center",
		alignItems: "center",
	},
	addPersonTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 10,
	},
	libraryTypeTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	libraryTypeCountTxt: {
		color: Colors.labelDarkGray,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsRegular,
	},
	headerAddBtn: {
		backgroundColor: "#e5e7e4",
		...CommonStyles.directionRowCenter,
		paddingVertical: 5,
		paddingLeft: 7,
		paddingRight: 10,
		borderRadius: 25,
	},
	headerAddbtnTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginLeft: 5,
	},
	starContainer: {
		padding: 10,
		backgroundColor: "#f8ece0",
		borderRadius: 7,
		marginRight: 10,
	},
	largeStarContainer: {
		padding: 20,
		backgroundColor: "#f8ece0",
		borderRadius: 7,
		marginRight: 10,
	},
	favTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	placesCounttxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
		lineHeight: 12,
	},
	favBottomBox: {
		top: deviceHeight / 1.68,
		...LayoutStyle.marginTop20,
		...LayoutStyle.paddingVertical10,
		...CommonStyles.directionRowSB,
		borderTopWidth: 1,
		borderTopColor: "#ccc",
	},
	favEditTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	addPlaceBtn: {
		backgroundColor: "#E5E5E5",
		padding: 5,
		justifyContent: "center",
		alignItems: "center",
		marginTop: "30%",
		...CommonStyles.directionRowCenter,
		borderRadius: 7,
		width: "35%",
		alignSelf: "center",
	},
	addPlaceTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 5,
		top: 1,
	},
	onlyRowSB: {
		flexDirection: "row",
		justifyContent: "space-between",
	},
	rowEnd: {
		...CommonStyles.directionRowCenter,
		justifyContent: "flex-end",
	},
	sortByTxt: {
		fontSize: 12,
		color: Colors.labelDarkGray,
		fontFamily: FontFamily.PoppinsRegular,
	},
	favPlaceBox: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingVertical10,
		flex: 1,
	},
	placeName: {
		color: Colors.labelBlack,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	placeImgBox: {
		height: 60,
		width: 60,
		borderRadius: 10,
	},
	placeImg: {
		height: "100%",
		width: "100%",
		resizeMode: "cover",
		borderRadius: 10,
	},
	placeDetailTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
		lineHeight: 18,
	},
	searchGuidePlace: {
		...CommonStyles.directionRowCenter,
		backgroundColor: "#e7e7e7",
		paddingLeft: 10,
		borderRadius: 5,
		flex: 1,
		height: 40,
		marginVertical: 20,
	},
	saveGuideTitle: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	guidePlaceBox: {
		flex: 1,
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingVertical10,
	},
	guideTextRow: {
		...LayoutStyle.paddingHorizontal10,
		width: "80%",
	},
	guideTitle: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	guideAddress: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	noRouteContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		marginTop: "50%",
	},
	noRouteTxtBox: {
		alignItems: "center",
		justifyContent: "center",
		marginVertical: 7,
	},
	customRouteTitle: {
		color: Colors.labelBlack,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsSemiBold,
		textAlign: "center",
	},
	routeDetail: {
		color: Colors.labelDarkGray,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsRegular,
		textAlign: "center",
	},
	createRouteBtn: {
		...CommonStyles.directionRowCenter,
		paddingHorizontal: 10,
		paddingVertical: 5,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#E8E8E8",
		borderRadius: 20,
	},
	createRouteTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginLeft: 5,
	},
	routeImgBox: {
		height: 220,
		width: "100%",
	},
	routeImg: {
		height: "100%",
		width: "100%",
		resizeMode: "contain",
	},
	chooseMap: {
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsSemiBold,
		fontSize: 20,
	},
	layoutOption: {
		width: "48%",
		borderWidth: 2,
		borderColor: Colors.secondary,
		borderRadius: 10,
		backgroundColor: Colors.white,
		elevation: 5,
	},
	layoutImgBox: {
		height: 70,
		width: "100%",
	},
	layoutImg: {
		height: "100%",
		width: "100%",
		borderTopLeftRadius: 10,
		borderTopRightRadius: 10,
	},
	layoutTxt: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		padding: 5,
	},
	mapLayoutRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginTop20,
	},
	locationRow: {
		...LayoutStyle.paddingVertical10,
		...CommonStyles.directionRowCenter,
	},
	locationTxtBox: {
		marginLeft: 10,
		flex: 1,
	},
	locationTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	distanceTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	locationDesTxt: {
		flex: 1,
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	directionHeaderBtn: {
		backgroundColor: "#e5e7e4",
		height: 28,
		width: 28,
		borderRadius: 14,
		justifyContent: "center",
		alignItems: "center",
	},
	navOptionBox: {
		flex: 1,
		marginHorizontal: 5,
		backgroundColor: "#E5E5E5",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 10,
		paddingVertical: 7,
	},
	directionOptionBox: {
		backgroundColor: "#E5E5E5",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 7,
		paddingVertical: 10,
		width: "17.5%",
	},
	navOptionTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginTop: 5,
		lineHeight: 16,
	},
	headerDesTxt: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	contactImg: {
		height: 30,
		width: 30,
		borderRadius: 15,
		backgroundColor: "#888",
		justifyContent: "center",
		alignItems: "center",
	},
	shortName: {
		color: Colors.white,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	addNoteTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	noteDes: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	destiSubTitle: {
		color: Colors.labelBlack,
		fontSize: 20,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	groupTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginLeft: 10,
		top: 2,
	},
	editBtnTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	blueDetailTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	directionDarkCircle: {
		height: 30,
		width: 30,
		borderRadius: 15,
		backgroundColor: "#E5E5E5",
		justifyContent: "center",
		alignItems: "center",
	},
	directionBlueCircle: {
		height: 16,
		width: 16,
		borderRadius: 8,
		backgroundColor: Colors.blueActiveBtn,
		justifyContent: "center",
		alignItems: "center",
	},
	selectedAddressText: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	onlyRowSB: {
		flexDirection: "row",
		justifyContent: "space-between",
	},
	reportBtnTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 10,
	},
	calendarBtn: {
		borderWidth: 1,
		borderColor: Colors.darkBorder,
		paddingVertical: 2,
		paddingHorizontal: 10,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 25,
		...CommonStyles.directionRowCenter,
		...LayoutStyle.marginRight10,
	},
	calendarTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
		marginRight: 10,
	},
	scheduleRow: {
		...CommonStyles.directionRowCenter,
		...LayoutStyle.marginBottom20,
	},
	etaBox: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.padding10,
	},
	etaTimeTxt: {
		color: Colors.labelBlack,
		fontSize: 20,
		fontFamily: FontFamily.PoppinsBold,
		// lineHeight: 20,
	},
	etaDistanceTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		lineHeight: 20,
	},
	etaTypeTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	goBtn: {
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 10,
		backgroundColor: "#4fd968",
		padding: 16,
	},
	goTxt: {
		color: Colors.white,
		fontSize: 20,
		fontFamily: FontFamily.PoppinsBold,
	},
	waypointsContainer: {
		backgroundColor: "#E5E5E5",
		...LayoutStyle.padding10,
		...LayoutStyle.marginVertical20,
		borderRadius: 7,
	},
	waypointIconContainer: {
		flex: 0.1,
		...LayoutStyle.paddingBottom10,
		top: 3,
		justifyContent: "center",
		alignItems: "center",
		marginRight: 10,
	},
	iconWrapper: {
		height: 20,
		width: 20,
		borderRadius: 10,
		backgroundColor: "#4fd968",
		justifyContent: "center",
		alignItems: "center",
	},
	waypointRow: {
		flex: 1,
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingVertical10,
		borderBottomWidth: 1,
		borderBottomColor: "#ccc",
	},
	waypoint: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	addStopRow: {
		flex: 0.9,
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingVertical10,
	},
	addStopTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
		top: 2,
	},
	pathDot: {
		height: 3,
		width: 3,
		borderRadius: 1.5,
		backgroundColor: "#888",
		alignSelf: "center",
		marginVertical: 1.5,
	},
	dotsContainer: {
		position: "absolute",
		top: "68%",
	},
	directionOptionRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginTop10,
	},
	flatLine: {
		height: 2,
		backgroundColor: Colors.labelDarkGray,
		width: "70%",
		borderRadius: 2,
		elevation: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -2 },
		shadowOpacity: 0.1,
		shadowRadius: 8,
	},
	emptyDirections: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		marginTop: "30%",
	},
	emptyTitle: {
		color: Colors.labelBlack,
		fontSize: 15,
		fontFamily: FontFamily.PoppinsBold,
		textAlign: "center",
	},
	emptyDes: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
		textAlign: "center",
	},
	learnMore: {
		fontSize: 14,
		color: Colors.blueActiveBtn,
		fontFamily: FontFamily.PoppinsMedium,
	},
	callBtn: {
		...CommonStyles.directionRowCenter,
		...LayoutStyle.paddingHorizontal20,
		backgroundColor: Colors.white,
		paddingVertical: 10,
		marginTop: 14,
		borderRadius: 7,
	},
	phoneTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 20,
		top: 1,
	},
	callModal: {
		position: "absolute",
		bottom: 20,
		left: 0,
		right: 0,
		paddingHorizontal: 20,
	},
	moreOptionContainer: {
		marginTop: 20,
		backgroundColor: Colors.white,
		borderRadius: 10,
		borderRadius: 10,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 5,
		borderTopWidth: 0,
		borderTopColor: "#ddd",
		zIndex: 999,
	},
	reportMoreOption: {
		marginTop: 10,
		backgroundColor: Colors.white,
		borderBottomLeftRadius: 10,
		borderBottomRightRadius: 10,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 5,
		borderTopWidth: 0,
		borderTopColor: "#ddd",
		zIndex: 999,
	},
	moreOptionRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingVertical10,
		...LayoutStyle.paddingHorizontal20,
	},
	moreOption: {
		color: Colors.labelBlack,
		fontSize: 15,
		fontFamily: FontFamily.PoppinsMedium,
	},
	headerCancelTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	reportPanelTitle: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsBold,
	},
	headerSend: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	issueTitle: {
		color: Colors.labelBlack,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsBold,
		marginVertical: 10,
	},
	issueTypeTxt: {
		color: Colors.labelBlack,
		fontSize: 15,
		fontFamily: FontFamily.PoppinsMedium,
	},
	nearyBySearchContainer: {
		...CommonStyles.directionRowCenter,
		backgroundColor: "#e7e7e7",
		...LayoutStyle.paddingHorizontal10,
		width: "88%",
		borderRadius: 5,
	},
	nearbyClose: {
		height: 24,
		width: 24,
		borderRadius: 12,
		backgroundColor: "#e7e7e7",
		justifyContent: "center",
		alignItems: "center",
	},
	nearByAddressName: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	nearByDesTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
	},
	distanceBox: {
		backgroundColor: "#E5E5E5",
		height: 60,
		width: 50,
		borderRadius: 7,
		justifyContent: "center",
		alignItems: "center",
	},
	nearByDistance: {
		color: Colors.blueActiveBtn,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
		top: 5,
	},
	distanceDirectionIcon: {
		height: 18,
		width: 18,
		borderRadius: 9,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: Colors.blueActiveBtn,
	},
	filterBtn: {
		paddingVertical: 6,
		paddingHorizontal: 10,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 20,
		borderWidth: 1,
		borderColor: Colors.labelDarkGray,
	},
	noteInput: {
		backgroundColor: Colors.white,
		padding: 10,
		borderRadius: 7,
		marginTop: 20,
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsRegular,
		minHeight: "50%",
		textAlignVertical: "top",
	},
	deleteNoteBtn: {
		backgroundColor: Colors.white,
		paddingVertical: 10,
		paddingHorizontal: 14,
		...CommonStyles.directionRowCenter,
		borderRadius: 7,
	},
	deleteIcon: {
		height: 30,
		width: 30,
		borderRadius: 15,
		backgroundColor: "#E5E5E5",
		justifyContent: "center",
		alignItems: "center",
		marginRight: 10,
	},
	deleteTxt: {
		color: Colors.red,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	addNoteScrollbar: {
		...LayoutStyle.paddingHorizontal20,
		paddingBottom: 20,
		flexGrow: 1,
		flexDirection: "column",
		justifyContent: "space-between",
	},
	pinWhiteContainer: {
		padding: 3,
		borderRadius: 999,
		backgroundColor: Colors.white,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 0.2,
		borderColor: Colors.labelDarkGray,

		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.5,
		shadowRadius: Platform.OS === "android" ? 10 : 35,
		elevation: 8,
	},
	pinIconContainer: {
		padding: 3,
		borderRadius: 999,
		backgroundColor: "#f50150",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 4,
	},
	swipeBtn: {
		width: 80,
		backgroundColor: "#DA4C4C",
		justifyContent: "center",
		alignItems: "center",
		borderBottomColor: "#ccc",
		borderBottomWidth: 1,
		marginLeft: 10,
	},
	swipeBtnTxt: {
		color: Colors.white,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	rowOnly: {
		flexDirection: "row",
		alignItems: "center",
	},
	turnRow: {
		...CommonStyles.directionRowCenter,
		...LayoutStyle.paddingVertical10,
	},
	topTurnRow: {
		...CommonStyles.directionRowCenter,
		...LayoutStyle.paddingVertical10,
		...LayoutStyle.paddingHorizontal20,
	},
	turnIcon: {
		justifyContent: "center",
		alignItems: "center",
		marginRight: 12,
	},
	turnDistacne: {
		fontSize: 16,
		color: Colors.labelBlack,
		fontFamily: FontFamily.PoppinsBold,
	},
	topTurnDistacne: {
		fontSize: 26,
		color: Colors.white,
		fontFamily: FontFamily.PoppinsBold,
	},
	trunDesTxt: {
		color: Colors.labelDarkGray,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
	},
	topTrunDesTxt: {
		color: Colors.white,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsMedium,
	},
	dTitleDetail: {
		color: Colors.labelBlack,
		fontSize: 28,
		fontFamily: FontFamily.PoppinsSemiBold,
		// lineHeight: 30,
	},
	dPanelTitle: {
		color: Colors.labelDarkGray,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
		top: Platform.OS === "android" ? -10 : 0,
	},
	dArrowBtn: {
		height: 32,
		width: 32,
		borderRadius: 16,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#E5E5E5",
	},
	destiTitleTxt: {
		color: Colors.labelBlack,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsSemiBold,
		lineHeight: 24,
	},
	destiArriveTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	optionIconContainer: {
		height: 36,
		width: 36,
		borderRadius: 18,
		backgroundColor: "#f50150",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 4,
	},
	endRouteBtn: {
		...LayoutStyle.marginVertical20,
		padding: 12,
		backgroundColor: "#ff3b2f",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 10,
	},
	endRouteTxt: {
		color: Colors.white,
		fontSize: 20,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	topPanelContainer: {
		position: "absolute",
		top: 0,
		width: "100%",
		// backgroundColor: "#1c1c1e",
		backgroundColor: "#313035",
		elevation: 10,
		zIndex: 999,
		overflow: "hidden",
	},
	dragHandle: {
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#1c1c1e",
		// backgroundColor: "#888",
	},

	dragBar: {
		width: 50,
		height: 6,
		borderRadius: 3,
		backgroundColor: "#ccc",
	},
	fixedBottomView: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		height: 60,
		backgroundColor: "#888",
		paddingHorizontal: 20,
		flexDirection: "row",
		alignItems: "center",
		zIndex: 10,
	},
	nextTurnRow: {
		...LayoutStyle.paddingHorizontal20,
		...CommonStyles.directionRowCenter,
		backgroundColor: "#888",
	},
	soundOptionTxtRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginHorizontal10,
		padding: 10,
	},
	soundOptionTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsRegular,
	},
	soundIconContainer: {
		...LayoutStyle.marginTop20,
		...LayoutStyle.marginHorizontal10,
		...CommonStyles.directionRowSB,
		backgroundColor: "#E5E5E5",
		padding: 10,
		borderRadius: 50,
	},
	rowWithMarginTop: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginTop10,
	},
	nearByHearRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginTop10,
		borderBottomWidth: 1,
		borderBottomColor: "#E5E5E5",
		paddingBottom: 10,
	},
	nearByTitle: {
		color: Colors.labelBlack,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsSemiBold,
		lineHeight: 18,
	},
	placeLengthTxt: {
		color: Colors.labelDarkGray,
		fontSize: 13,
		fontFamily: FontFamily.PoppinsMedium,
	},
	navNearbyPlace: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
		// lineHeight: 20,
	},
	navNearbyDes: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		lineHeight: 20,
	},
	nearByAddBtn: {
		backgroundColor: "#E5E5E5",
		paddingVertical: 5,
		paddingHorizontal: 14,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 5,
	},
	nearByAddTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
		top: 2.5,
	},
	noNearByPlace: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
		textAlign: "center",
	},
	ratingDistanceRow: {
		...CommonStyles.directionRowCenter,
		...LayoutStyle.marginVertical10,
		...LayoutStyle.paddingHorizontal10,
		paddingVertical: 5,
		borderTopWidth: 1,
		borderBottomWidth: 1,
		borderTopColor: "#E5E5E5",
		borderBottomWidth: 1,
		borderBottomColor: "#E5E5E5",
	},
	ratingBox: {
		borderRightWidth: 1,
		borderRightColor: "#E5E5E5",
		width: "35%",
	},
	placeRatingTxt: {
		color: Colors.labelDarkGray,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
		// lineHeight: 16,
	},
	orangeRating: {
		color: "#fe7002",
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginLeft: 5,
		top: 3,
	},
	distanceRouteTxt: {
		color: Colors.labelBlack,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginLeft: 10,
		top: 3,
	},
	columnSB: {
		flex: 1,
		flexDirection: "column",
		justifyContent: "space-between",
	},
	ratingBlack: {
		color: Colors.labelBlack,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsBold,
	},
	ratingBlackNum: {
		color: Colors.labelBlack,
		fontSize: 20,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	reviewBox: {
		backgroundColor: Colors.white,
		padding: 10,
		borderRadius: 5,
		height: 140,
		marginLeft: 10,
		maxWidth: 220,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 0,
		borderTopColor: "#ddd",
	},
	reviewTxt: {
		color: Colors.labelBlack,
		fontSize: 15,
		fontFamily: FontFamily.PoppinsMedium,
	},
	reviewProfileImg: {
		height: 30,
		width: 30,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	reviewImg: {
		height: "100%",
		width: "100%",
		resizeMode: "contain",
	},
	reviewPlaceImgBox: {
		height: 200,
		width: 155,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 7,
	},
	reviewPlaceImg: {
		height: "100%",
		width: "100%",
		resizeMode: "cover",
		borderRadius: 7,
	},
	reviewAuthor: {
		color: Colors.labelBlack,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
	},
	reviewCount: {
		color: Colors.labelDarkGray,
		fontSize: 12,
	},
	recentSwipeBtn: {
		flex: 1,
		height: "100%",
		backgroundColor: Colors.blueActiveBtn,
		...LayoutStyle.paddingHorizontal10,
		justifyContent: "center",
		alignItems: "center",
	},
	recentSwipeBtnTxt: {
		color: Colors.white,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	appsList: {
		flex: 1,
		justifyContent: "center",
		...LayoutStyle.paddingHorizontal20,
		...LayoutStyle.paddingVertical20,
	},
	appBox: {
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.marginRight20,
	},
	appImgBox: {
		backgroundColor: Colors.white,
		justifyContent: "center",
		alignItems: "center",
		height: 40,
		width: 40,
		padding: 5,
		borderRadius: 5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.15,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 1,
		borderTopColor: "#ddd",
	},
	appImg: {
		height: 25,
		width: 25,
	},
	appName: {
		fontSize: 10,
		marginTop: 5,
		fontFamily: FontFamily.PoppinsRegular,
	},
	shareAppModalBack: {
		flex: 1,
		justifyContent: "flex-end",
		backgroundColor: "rgba(0,0,0,0.3)",
	},
	shareAppWhiteBack: {
		height: 160,
		backgroundColor: "#fff",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		paddingHorizontal: 20,
		paddingVertical: 10,
	},
	selectedDestiIcon: {
		height: 30,
		width: 30,
		borderRadius: 15,
		...LayoutStyle.marginRight10,
		backgroundColor: "#f50150",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 4,
	},
	positionReletiveCenter: {
		position: "relative",
		alignItems: "center",
		justifyContent: "center",
	},
	indexContainer: {
		height: 12,
		width: 12,
		borderRadius: 6,
		backgroundColor: Colors.white,
		borderWidth: 0.5,
		borderColor: "#E5E5E5",
		position: "absolute",
		bottom: 0,
		right: -5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 8,
	},
	indexTxt: {
		fontSize: 10,
		fontFamily: FontFamily.PoppinsBold,
		color: Colors.labelBlack,
		textAlign: "center",
		textAlignVertical: "center",
		top: -1,
	},
	markTopBtn: {
		flex: 1,
		height: 53,
		paddingVertical: 10,
		borderRadius: 10,
		backgroundColor: Colors.blueActiveBtn,
		justifyContent: "center",
		alignItems: "center",
	},
	markTopBtnTxt: {
		color: Colors.white,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
		top: 5,
	},
	markTopDirectionBack: {
		padding: 2,
		backgroundColor: Colors.white,
		borderRadius: 20,
	},
	map: {
		...StyleSheet.absoluteFillObject,
	},
	mapWhiteBack: {
		height: "90%",
		backgroundColor: "#fff",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
	},
	markerHeader: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.paddingHorizontal20,
		...LayoutStyle.paddingVertical10,
	},
	mapCompContainer: {
		flex: 1,
		justifyContent: "space-between",
	},
	mapHeaderDesBox: {
		...LayoutStyle.paddingVertical10,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(204,204,204, 0.7)",
	},
	mapHeaderDes: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	mapNavIcon: {
		...LayoutStyle.margin20,
		backgroundColor: Colors.white,
		width: 40,
		height: 40,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 5,
	},
	removeLocContainer: {
		backgroundColor: Colors.white,
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.paddingVertical20,
	},
	removeLocTxt: {
		color: Colors.errorBoxRed,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	pinMarkerContainer: {
		padding: 7,
		justifyContent: "center",
		alignItems: "center",
	},
	redPin: {
		height: 40,
		width: 40,
		borderRadius: 20,
		backgroundColor: Colors.errorBoxRed,
		justifyContent: "center",
		alignItems: "center",
	},
	pinPoint: {
		position: "absolute",
		bottom: -6,
		zIndex: 999,
	},
	pinDot: {
		height: 5,
		width: 5,
		borderRadius: 2.5,
		backgroundColor: Colors.errorBoxRed,
		top: 7,
	},
	noDirection: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.paddingVertical20,
		marginTop: "15%",
	},
	alignCenter: {
		justifyContent: "center",
		alignItems: "center",
	},
	bigTitle: {
		color: Colors.labelBlack,
		fontSize: 28,
		fontFamily: FontFamily.PoppinsBold,
		width: "65%",
	},
	incidentTypeIcon: {
		height: 36,
		width: 36,
		borderRadius: 18,
		backgroundColor: Colors.errorBoxRed,
		justifyContent: "center",
		alignItems: "center",
	},
	incidentTypeTxt: {
		color: Colors.labelBlack,
		fontSize: 20,
		fontFamily: FontFamily.PoppinsMedium,
	},
	incidentTypeRow: {
		backgroundColor: Colors.white,
		padding: 10,
		borderRadius: 5,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 0,
		borderTopColor: "#ddd",
		...LayoutStyle.marginVertical10,
	},
	shareETADes: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	grayContactCircle: {
		backgroundColor: "#E5E5E5",
		height: 50,
		width: 50,
		borderRadius: 25,
		justifyContent: "center",
		alignItems: "center",
	},
	blueContactCircle: {
		backgroundColor: Colors.blueActiveBtn,
		padding: 5,
		borderRadius: 20,
	},
	openContactTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 18,
		fontFamily: FontFamily.PoppinsMedium,
	},
	headerTitleMedium: {
		color: Colors.labelBlack,
		fontSize: 20,
		fontFamily: FontFamily.PoppinsBold,
	},
	contactSearchRow: {
		...LayoutStyle.paddingHorizontal10,
		...CommonStyles.directionRowCenter,
		backgroundColor: "#E5E5E5",
		borderRadius: 7,
		alignItems: "center",
	},
	searchContact: {
		flex: 1,
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		paddingRight: 5,
		paddingVertical: 7,
	},
	contactName: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	contactNum: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	fLatterCircle: {
		height: 40,
		width: 40,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: Colors.primary,
	},
	fLatter: {
		fontFamily: FontFamily.PoppinsMedium,
		color: Colors.labelWhite,
		...LayoutStyle.fontSize20,
	},
	contactProfile: {
		width: 40,
		height: 40,
		borderRadius: 20,
		zIndex: -9,
	},
	smsTxt: {
		color: "#67c87f",
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	stopShareTxt: {
		color: Colors.errorBoxRed,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
	},
	shareLenghtBtn: {
		...LayoutStyle.marginTop10,
		...LayoutStyle.paddingVertical10,
		borderTopWidth: 1,
		borderTopColor: "#E5E5E5",
		justifyContent: "center",
		alignItems: "center",
	},
	shareLengthTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	headerBlueBtnTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	smallHeaderTitle: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	avoidBtnTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	recentlyViewTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
		marginBottom: 5,
	},
	libraryPlaceAction: {
		position: "absolute",
		bottom: Platform.OS === "ios" ? -85 : -145,
		right: 0,
		width: "70%",
		zIndex: 99,
		borderRadius: 10,
		backgroundColor: "#F5F5F5",
	},
	pinShareContainer: {
		backgroundColor: Colors.white,
		paddingVertical: 10,
		paddingHorizontal: 40,
		borderTopLeftRadius: 10,
		borderTopRightRadius: 10,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	actionBlackTxt: {
		color: Colors.labelBlack,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsRegular,
		marginTop: 10,
	},
	noteNDeleteContainer: {
		backgroundColor: Colors.white,
		paddingHorizontal: 10,
		marginTop: 10,
		borderBottomLeftRadius: 10,
		borderBottomRightRadius: 10,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	moreActionTxt: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	tripleDotActionBox: {
		position: "absolute",
		bottom: -340,
		right: 35,
		width: 220,
		zIndex: 99,
		borderRadius: 10,
		backgroundColor: "#F5F5F5",
	},
	tripleDotWhiteBox: {
		backgroundColor: Colors.white,
		...LayoutStyle.paddingVertical10,
		paddingHorizontal: 7,
		borderTopLeftRadius: 10,
		borderTopRightRadius: 10,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	tripleDotOptionBox: {
		backgroundColor: Colors.white,
		...LayoutStyle.paddingVertical10,
		...LayoutStyle.marginTop10,
		paddingHorizontal: 7,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	selectableIconBox: {
		width: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	gridActionTxt: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 7,
	},
	actionTitle: {
		color: Colors.labelDarkGray,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
	},
	searchPlaceRow: {
		...CommonStyles.directionRowSB,
		paddingVertical: 12,
		paddingHorizontal: 12,
	},
	multipleDltBox: {
		position: "absolute",
		right: 0,
		bottom: -45,
		zIndex: 999,
		width: 200,
		backgroundColor: Colors.white,
		...LayoutStyle.padding10,
		borderRadius: 7,
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	dltTxt: {
		color: Colors.errorBoxRed,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	gridContainer: {
		...LayoutStyle.marginTop20,
		gap: 10,
	},
	gridRow: {
		...CommonStyles.directionRowSB,
		...LayoutStyle.marginBottom10,
	},
	gridWhiteBox: {
		flex: 1,
		marginHorizontal: 5,
		backgroundColor: Colors.white,
		borderRadius: 10,
		width: "48%",
		shadowColor: "#888",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
		borderTopWidth: 0,
		borderTopColor: "#ddd",
	},
	gridPlaceImg: {
		height: 110,
		width: "100%",
		borderTopLeftRadius: 10,
		borderTopRightRadius: 10,
	},
	gridPlaceTitle: {
		color: Colors.labelBlack,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	gridPlaceAddrs: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	gridCheckIcon: {
		position: "absolute",
		right: 5,
		top: 5,
	},
	unpinGrayCircle: {
		backgroundColor: "#E5E5E5",
		height: 26,
		width: 26,
		borderRadius: 13,
		justifyContent: "center",
		alignItems: "center",
	},
	unpinPlaceTxt: {
		color: Colors.errorBoxRed,
		fontSize: 15,
		fontFamily: FontFamily.PoppinsMedium,
		...LayoutStyle.marginLeft10,
	},
	pinnedTxt: {
		color: Colors.labelDarkGray,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 3,
	},
	dimOverlay: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: "rgba(0,0,0,0.5)",
		zIndex: 5,
	},
	contactTypeBtn: {
		width: "49%",
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.padding10,
		borderBottomWidth: 1,
	},
	contactTypeTxt: {
		color: Colors.blueActiveBtn,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	divContact: {
		backgroundColor: "#ccc",
		height: "70%",
		width: 1,
	},
	phoneSearch: {
		backgroundColor: "#e7e7e7",
		paddingHorizontal: 10,
		borderRadius: 5,
		...CommonStyles.directionRowCenter,
		flex: 1,
		marginTop: 20,
	},
	trustedConTxt: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	trustedNameProfile: {
		height: 30,
		width: 30,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: Colors.primary,
		marginRight: 10,
	},
	singleCharTxt: {
		color: Colors.white,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsSemiBold,
	},
	trustedProfileCircle: {
		height: 30,
		width: 30,
		borderRadius: 15,
		...LayoutStyle.marginRight10,
		justifyContent: "center",
		alignItems: "center",
	},
	trustedProfileImg: {
		height: "100%",
		width: "100%",
		borderRadius: 30,
		resizeMode: "cover",
	},
	addingLibraryTxt: {
		color: Colors.labelDarkGray,
		fontSize: 12,
		fontFamily: FontFamily.PoppinsMedium,
		marginLeft: 5,
	},
	removePlaceWhite: {
		backgroundColor: Colors.white,
		marginTop: 20,
		borderRadius: 7,
		paddingTop: 14,
	},
	removePlaceTxt: {
		color: "#888",
		fontSize: 12,
		fontFamily: FontFamily.PoppinsSemiBold,
		textAlign: "center",
	},
	removePlaceDes: {
		color: Colors.labelDarkGray,
		fontSize: 11,
		fontFamily: FontFamily.PoppinsMedium,
		textAlign: "center",
	},
	removePlaceBtn: {
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.paddingVertical10,
	},
	removeTxt: {
		color: Colors.errorBoxRed,
		fontSize: 16,
		fontFamily: FontFamily.PoppinsMedium,
	},
	reachedIconRow: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.marginTop20,
	},
	analyticBoard: {
		backgroundColor: Colors.white,
		padding: 12,
		borderRadius: 12,
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		elevation: 5,
		width: "100%",
		marginVertical: 10,
	},
	previewContainer: {
		justifyContent: "center",
		alignItems: "flex-end",
		marginTop: 40,
		...LayoutStyle.paddingHorizontal20,
	},
	previewCard: {
		backgroundColor: Colors.white,
		...LayoutStyle.padding10,
		borderRadius: 7,
		alignItems: "center",
		shadowColor: "#000",
		shadowOpacity: 0.2,
		shadowRadius: 10,
		elevation: 5,
	},
	previewText: { fontSize: 22, marginBottom: 15 },
	recentPreview: {
		justifyContent: "center",
		alignItems: "center",
		...LayoutStyle.paddingHorizontal20,
	},
	closeButton: {
		backgroundColor: "black",
		paddingHorizontal: 20,
		paddingVertical: 10,
		borderRadius: 10,
	},
	prevPinContainer: {
		flex: 1,
		justifyContent: "center",
		backgroundColor: "rgba(0,0,0,0.4)",
	},
	prevActionRow: {
		...CommonStyles.directionRowSB,
		width: "60%",
	},
	prevEditTxt: {
		color: Colors.labelBlack,
		fontSize: 14,
		fontFamily: FontFamily.PoppinsMedium,
	},
	prevDiv: {
		height: 1,
		width: 220,
		backgroundColor: "#E5E5E5",
		marginVertical: 5,
	},
	recentPrevDiv: {
		width: "100%",
		height: 1,
		backgroundColor: "#ccc",
		marginVertical: 5,
	},
	recentPrevOption: {
		...LayoutStyle.padding10,
		...LayoutStyle.marginTop10,
		backgroundColor: "#dcdcdc",
		width: "70%",
		alignSelf: "flex-end",
		borderRadius: 7,
		alignItems: "center",
		shadowColor: "#000",
		shadowOpacity: 0.2,
		shadowRadius: 10,
		elevation: 5,
	},
	recentPrevRow: {
		...CommonStyles.directionRowSB,
		width: "100%",
	},
	rowFlexEnd: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-end",
	},
	endRouteModal: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		paddingHorizontal: 20,
		paddingVertical: 20,
		backgroundColor: Colors.white,
		borderTopLeftRadius: 16,
		borderTopRightRadius: 16,
	},
	endRouteMBtn: {
		backgroundColor: Colors.blueActiveBtn,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 8,
		width: "48%",
		borderRadius: 5,
	},
	endRouteBtnRow: {
		...CommonStyles.directionRowSB,
		paddingTop: 14,
	},
	searchContactBox: {
		backgroundColor: "#e7e7e7",
		paddingHorizontal: 10,
		borderRadius: 5,
		...CommonStyles.directionRowCenter,
		paddingVertical: Platform.OS === "ios" ? 10 : 0,
	},
});
