// List of trusted contact list
export const TRUST_CONTACT_LIST_REQUEST = "TRUST_CONTACT_LIST_REQUEST";
export const TRUST_CONTACT_LIST_SUCCESS = "TRUST_CONTACT_LIST_SUCCESS";
export const TRUST_CONTACT_LIST_FAIL = "TRUST_CONTACT_LIST_FAIL";

// Company employee list
export const COMPANY_EMPLOYEE_LIST_REQUEST = "COMPANY_EMPLOYEE_LIST_REQUEST";
export const COMPANY_EMPLOYEE_LIST_SUCCESS = "COMPANY_EMPLOYEE_LIST_SUCCESS";
export const COMPANY_EMPLOYEE_LIST_FAIL = "COMPANY_EMPLOYEE_LIST_FAIL";

// Pinned Contact list
export const PINNED_CONTACT_LIST_REQUEST = "PINNED_CONTACT_LIST_REQUEST";
export const PINNED_CONTACT_LIST_SUCCESS = "PINNED_CONTACT_LIST_SUCCESS";
export const PINNED_CONTACT_LIST_FAIL = "PINNED_CONTACT_LIST_FAIL";

// Admin Details
export const ADMIN_DETAIL_REQUEST = "ADMIN_DETAIL_REQUEST";
export const ADMIN_DETAIL_SUCCESS = "ADMIN_DETAIL_SUCCESS";
export const ADMIN_DETAIL_FAIL = "ADMIN_DETAIL_FAIL";

// get all passes
export const PASSES_LIST_REQUEST = "PASSES_LIST_REQUEST";
export const PASSES_LIST_SUCCESS = "PASSES_LIST_SUCCESS";
export const PASSES_LIST_FAIL = "PASSES_LIST_FAIL";

// Chat event receiver
export const SET_CHAT_EVENT = "SET_CHAT_EVENT";

// Chat user status receiver
export const SET_CHAT_USER_STATUS = "SET_CHAT_USER_STATUS";

// Chat user unread status
export const SET_CHAT_USER_MARKREAD_STATUS = "SET_CHAT_USER_MARKREAD_STATUS";

// Chat unread message count
export const SET_CHAT_UNREAD_COUNT = "SET_CHAT_UNREAD_COUNT";
