// update user profile
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

// remove user profile
export const REMOVE_PROFILE_REQUEST = "REMOVE_PROFILE_REQUEST";
export const REMOVE_PROFILE_SUCCESS = "REMOVE_PROFILE_SUCCESS";
export const REMOVE_PROFILE_FAIL = "REMOVE_PROFILE_FAIL";

// send otp on mobile number with token
export const SEND_OTP_TOKEN_REQUEST = "SEND_OTP_TOKEN_REQUEST";
export const SEND_OTP_TOKEN_SUCCESS = "SEND_OTP_TOKEN_SUCCESS";
export const SEND_OTP_TOKEN_FAIL = "SEND_OTP_TOKEN_FAIL";

// verify otp with token
export const VERIFY_2FA_TOKEN_REQUEST = "VERIFY_2FA_TOKEN_REQUEST";
export const VERIFY_2FA_TOKEN_SUCCESS = "VERIFY_2FA_TOKEN_SUCCESS";
export const VERIFY_2FA_TOKEN_FAIL = "VERIFY_2FA_TOKEN_FAIL";

// add trust contact
export const ADD_TRUST_CONTACT_REQUEST = "ADD_TRUST_CONTACT_REQUEST";
export const ADD_TRUST_CONTACT_SUCCESS = "ADD_TRUST_CONTACT_SUCCESS";
export const ADD_TRUST_CONTACT_FAIL = "ADD_TRUST_CONTACT_FAIL";

// List of trusted contact list
export const TRUST_CONTACT_LIST_REQUEST = "TRUST_CONTACT_LIST_REQUEST";
export const TRUST_CONTACT_LIST_SUCCESS = "TRUST_CONTACT_LIST_SUCCESS";
export const TRUST_CONTACT_LIST_FAIL = "TRUST_CONTACT_LIST_FAIL";

// list of policies
export const POLICY_LIST_REQUEST = "POLICY_LIST_REQUEST";
export const POLICY_LIST_SUCCESS = "POLICY_LIST_SUCCESS";
export const POLICY_LIST_FAIL = "POLICY_LIST_FAIL";

// list of policies
export const POLICY_DETAILS_REQUEST = "POLICY_DETAILS_REQUEST";
export const POLICY_DETAILS_SUCCESS = "POLICY_DETAILS_SUCCESS";
export const POLICY_DETAILS_FAIL = "POLICY_DETAILS_FAIL";

// password verify
export const VERIFY_PASSWD_REQUEST = "VERIFY_PASSWD_REQUEST";
export const VERIFY_PASSWD_SUCCESS = "VERIFY_PASSWD_SUCCESS";
export const VERIFY_PASSWD_FAIL = "VERIFY_PASSWD_FAIL";

export const RESET_APP = "RESET_APP";
