export const STORE_RECENET_LOCATION_LIST = "STORE_RECENET_LOCATION_LIST";
export const FETCH_RECENET_LOCATION_LIST = "FETCH_RECENET_LOCATION_LIST";
export const SET_RECENET_LOCATION_LIST = "SET_RECENET_LOCATION_LIST";
export const REMOVE_RECENET_LOCATION_LIST_ITEM =
	"REMOVE_RECENET_LOCATION_LIST_ITEM";
export const REMOVE_RECENET_LOCATION_LIST_ITEMS =
	"REMOVE_RECENET_LOCATION_LIST_ITEMS";

// Add place to library
export const STORE_LIBRARY_PLACE = "STORE_LIBRARY_PLACE";
export const FETCH_LIBRARY_PLACE = "FETCH_LIBRARY_PLACE";
export const SET_LIBRARY_PLACE = "SET_LIBRARY_PLACE";
export const REMOVE_LIBRARY_PLACE = "REMOVE_LIBRARY_PLACE";

// Pinned Places
export const PINNED_PLACE_LIST_REQUEST = "PINNED_PLACE_LIST_REQUEST";
export const PINNED_PLACE_LIST_SUCCESS = "PINNED_PLACE_LIST_SUCCESS";
export const PINNED_PLACE_LIST_FAIL = "PINNED_PLACE_LIST_FAIL";

// Map Layout Type

export const MAP_LAYOUT_TYPE = "MAP_LAYOUT_TYPE";
